baseURL = "https://hildersantos.com"
languageCode = "pt-br"
title = "Hilder Santos"

contentDir = "content"
layoutDir = "layouts"
publishDir = "public"

enableEmoji = true
enableRobotsTXT = true
googleAnalytics = "UA-970269-2"
disqusShortname = "hildersantos"
RemovePathAccents = true

[permalinks]
  posts = "/:year/:month/:slug/"
  pages = "/:slug/"