baseURL = "https://hildersantos.com"
languageCode = "pt-br"
title = "Hilder Santos"

archetypeDir = "archetypes"
contentDir = "content"
dataDir = "data"
layoutDir = "layouts"
publishDir = "dist"
themesDir = "themes"
staticDir = "public"

enableEmoji = true
enableRobotsTXT = true
googleAnalytics = "UA-970269-2"
disqusShortname = "hilderme"
RemovePathAccents = true

[permalinks]
  posts = "/:year/:month/:slug/"
  pages = "/:slug/"